poke_api/authors/urls.py
from django.urls import path 
from . import views


app_name = 'authors'

urlpatterns = [
    path('register/',views.register_view,name='register'),
    path('register/create',views.create_view,name='create'),
    path('login/',views.login_view,name='login'),
    path('login/create',views.login_create,name='login_create'),
    path('logout/',views.logout_view,name='logout'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('dashboard/pokemon/<int:id>/edit/',views.dashboard_pokemon_edit,name='dash_edit'),
    path('dashboard/pokemon/new',views.dashboard_pokemon_new,name='dashboard_pokemon_new'),
    path('dashboard/pokemon/<int:id>/delete/',views.dashboard_pokemon_delete,name='dash_delete')
]

poke_api/core/urls.py
from atexit import register
from django.db import router
from django.urls import include, path , re_path
from core import views
from rest_framework.routers import SimpleRouter
import oauth2_provider

pokemon_router = SimpleRouter()

pokemon_router.register('poke/api',views.PokeViewset,basename='poke-api')

tipo_router = SimpleRouter()

tipo_router.register('poke/api/tipo',views.TipoViewset,basename='tipo-api')


app_name = 'pokedex'


urlpatterns = [
    path('',views.home,name='home'),
    path('poke/search/',views.search,name='search'),
    path('poke/type/<int:tipo_id>/',views.tipo,name='tipo'),
    path('poke/<int:id>/',views.poke,name='pokemon'),
    path(r'o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('',include(pokemon_router.urls)),
    path('',include(tipo_router.urls))
]

poke_api/poke_api/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path , include, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('authors/',include('authors.urls')),
    path(r'o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    
    
    
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

poke_api/core/models.py
from email.policy import default
from django import views
from django.db import models
from django.contrib.auth.models import User
from django.forms import CharField
from django.contrib.auth.models import AbstractUser,BaseUserManager

class Pokedexmanager(BaseUserManager):
    def get_published(self):
        return self.filter(is_published=True).order_by('-id')

class Tipo(models.Model) :
    tipo = models.CharField(max_length=65)
    def __str__(self):
        return self.tipo

class Tipo_2(models.Model):
    tipo_2 = models.CharField(max_length=65)
    def __str__(self):
        return self.tipo_2

class Pokedex(models.Model) :
    objects = Pokedexmanager()
    name = models.CharField(max_length=65)
    desciption = models.CharField(max_length=165)
    slug = models.SlugField()
    rarity = models.CharField(max_length=20)
    mega_form = models.BooleanField()
    base_stats = models.ImageField(upload_to='pokemons/covers/%y/%m/%d')
    base_stats_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='pokemons/covers/%y/%m/%d',blank=True,default='')
    tipo = models.ForeignKey(Tipo,on_delete=models.SET_NULL,null=True,blank=True,default=None)
    tipo_2 =  models.ForeignKey(Tipo_2,on_delete=models.SET_NULL,null=True,blank=True,default=None)
    hunter = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    def __str__(self):
        return self.name



class User(models.Model):
    nome = models.CharField(max_length=25)
    sobrenome = models.CharField(max_length=35)
    senha = models.CharField(max_length=70)
    email = models.CharField(max_length=50)
# Create your models here.

poke_api/authors/forms/pokemon_form.py
from django import forms
from core.models import Pokedex
from authors.utils.django_form import add_attr
from collections import defaultdict


class AuthorRecipeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._my_errors = defaultdict(list)


        add_attr(self.fields.get('cover'), 'class', 'span-2')


class AuthorPokemonForm(forms.ModelForm):
    class Meta:
        model = Pokedex
        fields = ['name','desciption','rarity','mega_form','base_stats','base_stats_is_html','cover','tipo','tipo_2']


    


    def clean(self,*args, **kwargs):
        super_clean = super().clean(*args, **kwargs)
        cd = self.cleaned_data

        

        return super_clean

poke_api/core/views.py
from unicodedata import name
from django import http
from django.http import Http404
from django.shortcuts import render,get_list_or_404
from .models import Pokedex
from django.db.models import Q
from django.contrib import messages


def home(request):
    pokemons = Pokedex.objects.filter(is_published=True)

    messages.success(request,'otimo trabalho')

    return render(request,'pokemons/pages/home.html',context={
        'pokemons' : pokemons
    })

def tipo(request,tipo_id):
    pokemons = get_list_or_404(Pokedex.objects.filter(tipo__id=tipo_id,is_published=True).order_by('-id'))

    return render(request,'pokemons/pages/home.html',context={
        'pokemons' : pokemons,
        'type' : f'{pokemons[0].tipo.tipo}'
    })

def poke(request,id):
    pokemon_description = Pokedex.objects.filter(id=id,is_published=True).order_by('-id').first()
    return render(request,'pokemons/pages/poke-view.html',context={
        'pokemon' : pokemon_description,
        'is_detail_page' : True
    })

def search(request):
    search_term = request.GET.get('q','').strip()

    if not search_term:
        raise Http404()

    pokemons = Pokedex.objects.filter(
        Q(
            Q(name__icontains=search_term)
        ),
        is_published=True
    ).order_by('-id')
        
    

    return render(request,'pokemons/pages/search.html',{
        'page_title' : f'Search for {search_term}',
        'search_term' : search_term,
        'recipes' : pokemons,
    })
    

# Create your views here.

poke_api/core/views/api.py
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from ..models import Pokedex, Tipo
from rest_framework import status
from ..serializers import Poke_serializer, Tipo_serializer
from rest_framework.viewsets import ModelViewSet
from oauth2_provider.contrib.rest_framework import TokenHasReadWriteScope, OAuth2Authentication
from rest_framework.authentication import SessionAuthentication 
from rest_condition import Or
from rest_framework.permissions import IsAdminUser


class PokeViewset(ModelViewSet):
    queryset = Pokedex.objects.get_published()
    serializer_class = Poke_serializer
    authentication_classes = [OAuth2Authentication, SessionAuthentication]
    permission_classes = [Or(IsAdminUser, TokenHasReadWriteScope)]

class TipoViewset(ModelViewSet):
    queryset = Tipo.objects.all()
    serializer_class = Tipo_serializer
    

poke_api/core/views/site.py
from unicodedata import name
from django import http
from django.http import Http404, HttpResponse
from django.shortcuts import render,get_list_or_404
from ..models import Pokedex
from django.db.models import Q
from django.contrib import messages
from rest_framework.decorators import api_view
from rest_framework.response import Response


def home(request):
    pokemons = Pokedex.objects.filter(is_published=True)

    messages.success(request,'otimo trabalho')

    return render(request,'pokemons/pages/home.html',context={
        'pokemons' : pokemons
    })

def tipo(request,tipo_id):
    pokemons = get_list_or_404(Pokedex.objects.filter(tipo__id=tipo_id,is_published=True).order_by('-id'))

    return render(request,'pokemons/pages/home.html',context={
        'pokemons' : pokemons,
        'type' : f'{pokemons[0].tipo.tipo}'
    })

def poke(request,id):
    pokemon_description = Pokedex.objects.filter(id=id,is_published=True).order_by('-id').first()
    return render(request,'pokemons/pages/poke-view.html',context={
        'pokemon' : pokemon_description,
        'is_detail_page' : True
    })

def search(request):
    search_term = request.GET.get('q','').strip()

    if not search_term:
        raise Http404()

    pokemons = Pokedex.objects.filter(
        Q(
            Q(name__icontains=search_term)
        ),
        is_published=True
    ).order_by('-id')
        
    

    return render(request,'pokemons/pages/search.html',{
        'page_title' : f'Search for {search_term}',
        'search_term' : search_term,
        'recipes' : pokemons,
    })
    




# Create your views here.

poke_api/core/templates/pokemons/partials/footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="https://github.com/drakosilva" target="_blank" rel="noreferrer noopener">By guilherme maciel</a>
    </div>
  
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
  </footer> 

poke_api/core/templates/pokemons/partials/head.html
{% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/fontawesome.min.css" integrity="sha512-xX2rYBFJSj86W54Fyv1de80DWBq7zYLn2z0I9bIhQG+rxIF6XVJUpdGnsNHWRa6AvP89vtFupEPDP8eZAtu9qA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/solid.min.css" integrity="sha512-qzgHTQ60z8RJitD5a28/c47in6WlHGuyRvMusdnuWWBB6fZ0DWG/KyfchGSBlLVeqAz+1LzNq+gGZkCSHnSd3g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
    rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/brands.min.js" integrity="sha512-KGeeDLRAGeJZYsq3J/4s/X6eZyaxTAlScSN2b7z/H/r2MBZ3pAg4T52SzavEJa2Uthmll5HMhvRaLeuxT76EVQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://code.iconify.design/2/2.2.1/iconify.min.js"></script>
    <link rel="stylesheet" href="{% static 'poke_api/css/styles.css' %}">
    

poke_api/core/templates/pokemons/partials/header.html
<header class="main-header-conteiner">
    <div class="main-header conteiner">
        <h1>
            <a  class="main-logo" href="{% url 'pokedex:home' %}">
                <span class="iconify main-logo-icon" data-icon="mdi:pokeball"></span> 
                <span class="main-logo-text">Pokedex</span>
            </a>
        </h1>
    </div>
</header>

poke_api/core/templates/pokemons/partials/menu.html
<button class="button-show-menu button-show-menu-visible">
    <i class="fas fa-bars"></i>
    <span class="hidden-text">Show menu</span>
  </button>
  
  <div class="menu-container menu-hidden">
    <button class="button-close-menu button-close-menu-visible">
      <i class="fas fa-times-circle"></i>
      <span class="hidden-text">Close menu</span>
    </button>
  
    <div class="menu-content">
      <nav class="menu-nav">
        <a href="{% url 'pokedex:home' %}">Home</a>
  
        {% if user.is_authenticated %}
          <a href="{% url 'authors:dashboard_pokemon_new' %}">New recipe</a>
          <a href="{% url 'authors:dashboard' %}">Dashboard</a>
          <a href="{% url 'authors:logout' %}">Logout</a>
        {% else %}
          <a href="{% url 'authors:login' %}">Login</a>
          <a href="{% url 'authors:register' %}">Register</a>
      {% endif %}
      </nav>
    </div>
  </div> 

poke_api/core/templates/pokemons/partials/pagination.html
{% if pokemons.has_other_pages %}
        {% for page in pagination_range.pagination  %}
            <div class=" pagination">
                {{ page }}
            </div>
        {% endfor %}
{% endif %}

poke_api/core/templates/pokemons/partials/poke_card.html
        
        <div class="pok pok-list-item">
            <div class="pok-cover">
            <a href="{% url 'pokedex:pokemon' pokemon.id %}">
                <img src="{{ pokemon.cover.url }}"alt="Temporario">
            </a>
            </div>
            <div class="pok-name-conteiner">
            <h5 class="pok-name">
                <a href="{% url 'pokedex:pokemon' pokemon.id %}">
                    <div class="pok-name">{{ pokemon.name }}</div>
                </a>
            </h5>
                {% if pokemon.hunter.first_name %}
                <div class="recipe-author">
                    <span class="recipe-author-item">
                        <i class="fas fa-user"></i>
                        {{ pokemon.hunter.first_name }}
                    </span>
                {% else %}
                    {{ pokemon.hunter.username }}
                {% endif %}
                    <span class="recipe-author-item">
                        <i class="fas fa-calendar-alt"></i>
                        {{ pokemon.created_at|date:"d/m/Y" }} às {{ pokemon.created_at|date:"H:i" }}
                    </span>
                    {% if pokemon.tipo is not None %}
                        <span class="recipe-author-item">
                            <a href="{% url 'pokedex:tipo' pokemon.tipo.id%}">
                                <i class="fas fa-layer-group"></i>
                               {% if tipo_2 is True %}
                                    <span>{{ pokemon.tipo.tipo }}-{{ pokemon.tipo_2.tipo_2 }}}</span>
                                    {% else %}
                                        <span>{{ pokemon.tipo.tipo }}</span>
                                {% endif %}    
                                
                               
                            </a>
                        </span>
                    {% endif %}
                </div>

                <div class="poke-content">
                    <p>{{ pokemon.description }}</p>
                </div>
                <div class="poke-meta-conteiner">
                    <div class="poke-meta pok-rarity">
                        <h3 class="poke-meta-title">Raridade</h3>
                        <div class="poke-meta-text">
                            {{ pokemon.rarity }}
                        </div>
                    </div>
                    <div class="poke-meta pok-alternativr-form">
                        <h3 class="poke-meta-title"><i class="pksymbol pksymbol-form-mega2"></i> mega forma</h3>
                        <div class="poke-meta-text">
                            {{ pokemon.mega_form }}
                        </div>
                    </div>                                               
                </div>
            {% if is_detail_page is not True %}
                    <footer class="recipe-footer">
                        <a class="recipe-read-more button button-dark button-full-width" href="{% url 'pokedex:pokemon' pokemon.id %}">
                            <i class="fas fa-eye"></i>
                            <span>ver mais...</span>
                        </a>
                    </footer>
            {% endif %}
            
            {% if is_detail_page is True %}
            <div class="base-stats">
                <a href="{% url 'pokedex:pokemon' pokemon.id %}">
                    <img class="base-stats-img" src="{{ pokemon.base_stats.url }}"alt="Temporario">
            </div>
            {% endif %} 

            
            </div>
        </div>

poke_api/core/templates/pokemons/partials/search.html
<div class="search-conteiner">
    <div class="conteiner">
        <form  action="{% url 'pokedex:search'  %}" method="GET" class="search-form">
            <input type="search" class="search-input" name="q" value="{{ search_term }}" required>
            <button type="submit" class="search_button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>