poke_api/authors/urls.py
from django.urls import path 
from . import views


app_name = 'authors'

urlpatterns = [
    path('register/',views.register_view,name='register'),
    path('register/create',views.create_view,name='create'),
    path('login/',views.login_view,name='login'),
    path('login/create',views.login_create,name='login_create'),
    path('logout/',views.logout_view,name='logout'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('dashboard/pokemon/<int:id>/edit/',views.dashboard_pokemon_edit,name='dash_edit'),
    path('dashboard/pokemon/new',views.dashboard_pokemon_new,name='dashboard_pokemon_new'),
    path('dashboard/pokemon/<int:id>/delete/',views.dashboard_pokemon_delete,name='dash_delete')
]

poke_api/core/urls.py
from atexit import register
from django.db import router
from django.urls import include, path , re_path
from core import views
from rest_framework.routers import SimpleRouter
import oauth2_provider

pokemon_router = SimpleRouter()

pokemon_router.register('poke/api',views.PokeViewset,basename='poke-api')

tipo_router = SimpleRouter()

tipo_router.register('poke/api/tipo',views.TipoViewset,basename='tipo-api')


app_name = 'pokedex'


urlpatterns = [
    path('',views.home,name='home'),
    path('poke/search/',views.search,name='search'),
    path('poke/type/<int:tipo_id>/',views.tipo,name='tipo'),
    path('poke/<int:id>/',views.poke,name='pokemon'),
    path(r'o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('',include(pokemon_router.urls)),
    path('',include(tipo_router.urls))
]

poke_api/poke_api/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path , include, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('authors/',include('authors.urls')),
    path(r'o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    
    
    
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

poke_api/authors/models.py
from django.db import models

# Create your models here.

poke_api/authors/forms.py
import re
from django.core.exceptions import ValidationError
from django import forms
from django.contrib.auth.models import User

def add_attr(field,attr_name,attr_new_value):
    existing_attr = field.widget.attrs.get(attr_name,'')
    field.widget.attrs[attr_name] = f'{existing_attr} {attr_new_value}'.strip()

def add_placeholder(field,placeholder_val):
    add_attr(field,'placeholder',placeholder_val)


def strong_password(password):
    regex = re.compile(r'^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{8,}$')

    if not regex.match(password):
        raise ValidationError(
            'The password must be at least eight characters long, including at least one number or special character, and must not be too common.',
            code='Invalid'
        )

class Register_user(forms.ModelForm):
    def __init__(self,*args, **kwargs ):
        super().__init__(*args, **kwargs)
        add_attr(self.fields['username'],'placeholder','your username')
        add_placeholder(self.fields['email'],'your email')
        add_placeholder(self.fields['first_name'],'ex. : john')
        add_placeholder(self.fields['last_name'],'ex. : doe')

    password_2 = forms.CharField( max_length=15, required=True,widget=forms.PasswordInput(attrs={'placeholder' : 'repeat your password'}),validators=[strong_password] )
    password = forms.CharField( max_length=15, required=True,widget=forms.PasswordInput(attrs={'placeholder' : 'send your password'}))


    first_name = forms.CharField(
        error_messages={'required': 'Write your first name'},
        label='First name'
    )
    last_name = forms.CharField(
        error_messages={'required': 'Write your last name'},
        label='Last name'
    )
    email = forms.EmailField(
        error_messages={'required': 'E-mail is required'},
        label='E-mail',
        help_text='The e-mail must be valid.',
    )
    class Meta():
        model = User
        fields = ['first_name','last_name','username','email','password']


        widgets = {
            'first_name' : forms.TextInput(attrs={
                'placeholder' : 'type your name here',
            
            }),
            'password' : forms.PasswordInput(attrs={
                'placeholder' : 'type your password here'
            })
        }


    def clean_email(self):
        data = self.cleaned_data.get('email','')
        exists = User.objects.filter(email=data).exists()

        if exists:
            raise ValidationError('User email is already in use',code='Invalid')

        return data




    def clean(self):
        cleaned_data = super().clean()

        password = cleaned_data.get('password')
        password_2 = cleaned_data.get('password_2')

        if password != password_2 :
            password_confirmation_error = ValidationError('Password is not equal of password_2',code='invalid')
            raise ValidationError({
                'password' : password_confirmation_error,
                'password_2' : [
                    password_confirmation_error,
                    'another error'
                ]
            })

poke_api/authors/forms/login.py
from django import forms
from authors.utils.django_form import add_placeholder


class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['username'], 'Type your username')
        add_placeholder(self.fields['password'], 'Type your password')

    username = forms.CharField()
    password = forms.CharField(
        widget=forms.PasswordInput()
    )

poke_api/authors/forms/pokemon_form.py
from django import forms
from core.models import Pokedex
from authors.utils.django_form import add_attr
from collections import defaultdict


class AuthorRecipeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._my_errors = defaultdict(list)


        add_attr(self.fields.get('cover'), 'class', 'span-2')


class AuthorPokemonForm(forms.ModelForm):
    class Meta:
        model = Pokedex
        fields = ['name','desciption','rarity','mega_form','base_stats','base_stats_is_html','cover','tipo','tipo_2']


    


    def clean(self,*args, **kwargs):
        super_clean = super().clean(*args, **kwargs)
        cd = self.cleaned_data

        

        return super_clean

poke_api/authors/forms/register_form.py
from authors.utils.django_form import add_attr,add_placeholder,strong_password
from django.core.exceptions import ValidationError
from django import forms
from django.contrib.auth.models import User


class Register_user(forms.ModelForm):
    def __init__(self,*args, **kwargs ):
        super().__init__(*args, **kwargs)
        add_attr(self.fields['username'],'placeholder','your username')
        add_placeholder(self.fields['email'],'your email')
        add_placeholder(self.fields['first_name'],'ex. : john')
        add_placeholder(self.fields['last_name'],'ex. : doe')

    password_2 = forms.CharField( max_length=15, required=True,widget=forms.PasswordInput(attrs={'placeholder' : 'repeat your password'}),validators=[strong_password] )
    password = forms.CharField( max_length=15, required=True,widget=forms.PasswordInput(attrs={'placeholder' : 'send your password'}))


    first_name = forms.CharField(
        error_messages={'required': 'Write your first name'},
        label='First name'
    )
    last_name = forms.CharField(
        error_messages={'required': 'Write your last name'},
        label='Last name'
    )
    email = forms.EmailField(
        error_messages={'required': 'E-mail is required'},
        label='E-mail',
        help_text='The e-mail must be valid.',
    )
    class Meta():
        model = User
        fields = ['first_name','last_name','username','email','password']


        widgets = {
            'first_name' : forms.TextInput(attrs={
                'placeholder' : 'type your name here',
            
            }),
            'password' : forms.PasswordInput(attrs={
                'placeholder' : 'type your password here'
            })
        }


    def clean_email(self):
        data = self.cleaned_data.get('email','')
        exists = User.objects.filter(email=data).exists()

        if exists:
            raise ValidationError('User email is already in use',code='Invalid')

        return data




    def clean(self):
        cleaned_data = super().clean()

        password = cleaned_data.get('password')
        password_2 = cleaned_data.get('password_2')

        if password != password_2 :
            password_confirmation_error = ValidationError('Password is not equal of password_2',code='invalid')
            raise ValidationError({
                'password' : password_confirmation_error,
                'password_2' : [
                    password_confirmation_error,
                    'another error'
                ]
            })

poke_api/authors/views.py
from django.urls import reverse
from django.contrib import messages
from django.shortcuts import redirect, render
from .forms import Register_user,LoginForm,AuthorPokemonForm
from django.http import Http404
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from core.models import Pokedex

def register_view(request):
    register_form_data = request.session.get('register_form_data',None)
    form = Register_user(register_form_data)
    return render(request,'pages/register_view.html',{
        'form' : form
    })
    
def create_view(request):
    if not request.POST:
        raise Http404


    POST = request.POST

    request.session['register_form_data'] = POST

    form = Register_user(POST)

    if form.is_valid():
        user = form.save(commit=False)
        user.set_password(user.password)
        user.save()

        
        messages.success(request,'your user is created! , please log in.')

        del(request.session['register_form_data'])
        return redirect(reverse('authors:login'))

    return redirect('authors:register')


def login_view(request):
    form = LoginForm()
    return render (request,'pages/login_view.html',{
        'form' : form,
        'form_action' : reverse('authors:login_create')
    })

def login_create(request):
    if not request.POST:
        raise Http404()

    form = LoginForm(request.POST)
    login_url = reverse('authors:login')

    if form.is_valid():
        authenticated_user = authenticate(
            username=form.cleaned_data.get('username', ''),
            password=form.cleaned_data.get('password', ''),
        )

        if authenticated_user is not None:
            messages.success(request, 'Your are logged in.')
            login(request, authenticated_user)
        else:
            messages.error(request, 'Invalid credentials')
    else:
        messages.error(request, 'Invalid username or password')

    return redirect(login_url)

@login_required(login_url='authors:login',redirect_field_name='next')
def logout_view(request):
    if not request.POST:
        return redirect(reverse('authors:login'))

    if request.POST.get('username') != request.user.username:
        return redirect(reverse('authors:login'))


    logout(request)
    return redirect(reverse('authors:login'))


@login_required(login_url='authors:login',redirect_field_name='next')
def dashboard(request):
    pokemons = Pokedex.objects.filter(
        is_published=False,
        hunter=request.user
    )
    return render(request,'pages/dashboard.html',context={
        'pokemons' : pokemons
    })

@login_required(login_url='authors:login',redirect_field_name='next')
def dashboard_pokemon_edit(request,id):
    pokemon = Pokedex.objects.filter(
        is_published=False,
        hunter=request.user,
        pk=id
    ).first()

    if not pokemon:
        raise Http404

    form = AuthorPokemonForm(
        request.POST or None,
        files= request.FILES or None,
        instance=pokemon
    )


    if form.is_valid():
        pokemon = form.save(commit=False)

        pokemon.hunter = request.user
        pokemon.base_stats_is_html = False
        pokemon.is_published = False

        pokemon.save()

        messages.success(request,'your pokemon add for pokedex')

        return redirect(reverse('authors:dash_edit',args=(id,)))


    return render(request,'pages/dashboard_pokemon.html',context={
        'form' : form
    })


@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard_pokemon_new(request):
    form = AuthorPokemonForm(
        data=request.POST or None,
        files=request.FILES or None,
    )

    if form.is_valid():
        pokemon = form.save(commit=False)

        pokemon.hunter = request.user
        pokemon.base_stats_steps_is_html = False
        pokemon.is_published = False

        pokemon.save()

        messages.success(request, 'Salvo com sucesso!')
        return redirect(
            reverse('authors:dash_edit', args=(pokemon.id,))
        )

    return render(
        request,
        'pages/dashboard_pokemon.html',
        context={
            'form': form,
            'form_action': reverse('authors:dashboard_pokemon_new')
        }
    )


@login_required(login_url='authors:login',redirect_field_name='next')
def dashboard_pokemon_delete(request,id):

    pokemon = Pokedex.objects.filter(
        is_published=False,
        hunter=request.user,
        pk=id
    ).first()

    if not pokemon:
        raise Http404

    pokemon.delete()
    messages.success(request,'Deleted sucessfully')
    return redirect(reverse('authors:dashboard'))


# Create your views here.

poke_api/authors/templates/pages/dashboard.html
{% extends 'global/base.html' %}

{% block title %}Dashboard ({{ user }}) | {% endblock title %}

{% block content %}
  <div class="main-content center container">
    <h2>Dashboard ({{ user }})</h2>
    {% include 'global/login_message.html' %}

    <div class="authors-dashboard-conteiner">
      <h3>your pokemons</h3>

      <ul>
        {% for pokemon in pokemons  %}
          <li>
            <a href="{% url 'authors:dash_edit' pokemon.id %}">{{ pokemon.name }}</a>-
            <form action="{% url 'authors:dash_delete' pokemon.id %}" class="inline-form form-delete" method="POST"> {% csrf_token %}
              <button type="submit" class='plaintext-button'>❌</button>
            </form>
          </li>
        {% empty %}
          <li>
            <p>You didn't catch any pokemon</p>
          </li>
        {% endfor %}

      </ul>
    </div>
  </div>

  {% include 'global/messages.html' %}

  {% endblock content %} 

poke_api/authors/templates/pages/dashboard_pokemon.html
{% extends 'global/base.html' %}

{% block title %}Dashboard Pokemon | {% endblock title %}

{% block content %}
  <div class="main-content center container">
    <h2>Dashboard Pokemon</h2>
    {% include 'global/messages.html' %}
    {% include 'global/login_message.html' %}

    <div class="left">
      {% include 'global/form.html' %}
    </div>
  </div>


  {% endblock content %} 

poke_api/authors/templates/pages/head.html
{% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/fontawesome.min.css" integrity="sha512-xX2rYBFJSj86W54Fyv1de80DWBq7zYLn2z0I9bIhQG+rxIF6XVJUpdGnsNHWRa6AvP89vtFupEPDP8eZAtu9qA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/solid.min.css" integrity="sha512-qzgHTQ60z8RJitD5a28/c47in6WlHGuyRvMusdnuWWBB6fZ0DWG/KyfchGSBlLVeqAz+1LzNq+gGZkCSHnSd3g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
    rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'poke_api/css/styles.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/brands.min.js" integrity="sha512-KGeeDLRAGeJZYsq3J/4s/X6eZyaxTAlScSN2b7z/H/r2MBZ3pAg4T52SzavEJa2Uthmll5HMhvRaLeuxT76EVQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://code.iconify.design/2/2.2.1/iconify.min.js"></script>
    

poke_api/authors/templates/pages/login_view.html
{% extends 'global/base.html' %}
{% block title %}Login | {% endblock title %}
{% block content %}
  <div class="main-content center container">
    <h2>Login</h2>
    {% include 'global/login_message.html' %}
  </div>

  {% include 'global/messages.html' %}
  {% if not user.is_authenticated %}
    {% include 'global/form.html' %}
  {% endif %}
{% endblock content %}

poke_api/authors/templates/pages/menu.html
<button class="button-show-menu button-show-menu-visible">
    <i class="fas fa-bars"></i>
    <span class="hidden-text">Show menu</span>
  </button>
  
  <div class="menu-container menu-hidden">
    <button class="button-show-menu button-show-menu-visible">
      <i class="fas fa-times-circle"></i>
      <span class="hidden-text">Close menu</span>
    </button>
  
    <div class="menu-content">
      <nav class="menu-nav">
        <a href="{% url 'pokedex:home' %}">Home</a>
  
        {% if user.is_authenticated %}
          <a href="{% url 'authors:dashboard_pokemon_new' %}">New recipe</a>
          <a href="{% url 'authors:dashboard' %}">Dashboard</a>
          <a href="{% url 'authors:logout' %}">Logout</a>
        {% else %}
          <a href="{% url 'authors:login' %}">Login</a>
          <a href="{% url 'authors:register' %}">Register</a>
      {% endif %}
      </nav>
    </div>
  </div> 

poke_api/authors/templates/pages/register_view.html
{% extends 'global/base.html' %}

{% load static %}

{% block title %}Register | {% endblock title %}

{% block content %}
  <div class="main-content center container">
    <h2>Register</h2>
  </div>


  <div class="main-content container">
    <form action="{% url 'authors:create' %}" method="POST">{% csrf_token %}

      <div class="form-content form-content-grid">
        {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{field}}

            {% if field.help_text %}
              <p class="help-text">{{ field.help_text }}</p>
            {% endif %}

            {{ field.errors }}
          </div>
        {% endfor %}
      </div>
      {% if form.errors %}
        <div class="form-content form-content-grid">
          <div class="form-group">
            <div class="massage massage-error">
              Please fix the errors in the formulary
            </div>
          </div>
        </div>
      {% endif %}
      <div class="form-content form-content-grid">
        <div class="form-group">
          <button type="submit">Send</button>
        </div>
      </div>
    </form>
  </div>
{% endblock content %} 